name: PlaytimePlus
version: 1.2
main: main.java.com.playtime.PlaytimePlus
author: YourName
description: Displays playtime in chat and restricts item usage by playtime
softdepend: [PermissionsEx, GroupManager, Essentials]
commands:
  playtime:
    description: Check your playtime or another player's playtime
    usage: /playtime [player]
    aliases: [pt]
  pt:
    description: Check your playtime or another player's playtime
    usage: /pt [player]
permissions:
  playtimeplus.admin:
    description: Bypass block placement restrictions
    default: false
  playtimeplus.view.others:
    description: View other players' playtime
    default: false